/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppVehicleIdRouteImport } from './routes/app.vehicle.$id'
import { Route as ApiPublicGcalCallbackRouteImport } from './routes/api.public.gcal.callback'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/app/reports',
  path: '/app/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/app/analytics',
  path: '/app/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVehicleIdRoute = AppVehicleIdRouteImport.update({
  id: '/app/vehicle/$id',
  path: '/app/vehicle/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGcalCallbackRoute = ApiPublicGcalCallbackRouteImport.update({
  id: '/api/public/gcal/callback',
  path: '/api/public/gcal/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/vehicle/$id': typeof AppVehicleIdRoute
  '/api/public/gcal/callback': typeof ApiPublicGcalCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/vehicle/$id': typeof AppVehicleIdRoute
  '/api/public/gcal/callback': typeof ApiPublicGcalCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/vehicle/$id': typeof AppVehicleIdRoute
  '/api/public/gcal/callback': typeof ApiPublicGcalCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app/analytics'
    | '/app/reports'
    | '/app/settings'
    | '/app/'
    | '/app/vehicle/$id'
    | '/api/public/gcal/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/analytics'
    | '/app/reports'
    | '/app/settings'
    | '/app'
    | '/app/vehicle/$id'
    | '/api/public/gcal/callback'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/app/analytics'
    | '/app/reports'
    | '/app/settings'
    | '/app/'
    | '/app/vehicle/$id'
    | '/api/public/gcal/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppVehicleIdRoute: typeof AppVehicleIdRoute
  ApiPublicGcalCallbackRoute: typeof ApiPublicGcalCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/app/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/app/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/vehicle/$id': {
      id: '/app/vehicle/$id'
      path: '/app/vehicle/$id'
      fullPath: '/app/vehicle/$id'
      preLoaderRoute: typeof AppVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gcal/callback': {
      id: '/api/public/gcal/callback'
      path: '/api/public/gcal/callback'
      fullPath: '/api/public/gcal/callback'
      preLoaderRoute: typeof ApiPublicGcalCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppVehicleIdRoute: AppVehicleIdRoute,
  ApiPublicGcalCallbackRoute: ApiPublicGcalCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
